### ISSUE TITLE
Integrate Nutri-Patrol in all the places (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/nutripatrol#58]
```[tasklist]
### Integrate Nutri-Patrol in all the places
- [ ] Integrate Nutri-Patrol in Hunger Games
- [ ] https://github.com/openfoodfacts/nutripatrol/issues/56
- [ ] Integrate Nutri-Patrol in The Open Food Facts mobile app
- [ ] Integrate Nutri-Patrol in 3rd party apps
- [ ] Integrate Nutri-Patrol in Open Prices
- [ ] https://github.com/openfoodfacts/openfoodfacts-dart/issues/885
- [ ] https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/270
- [ ] https://github.com/openfoodfacts/power-user-script/issues/58
- [ ] https://github.com/openfoodfacts/openfoodfacts-nodejs/issues/182
- [ ] https://github.com/openfoodfacts/openfoodfacts-server/issues/1408
- [ ] Create a Nutri-Patrol knowledge panel
```

### Part of
- #24
